/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { readCultivationResponse } from "./cultivationApi.js";
import "../csss/CultivationMarketplace.css";
import "../csss/CultivationAudit.css";
const PAGE_SIZE = 10;
const statusKeys = { pending: "pendingReview", accepted: "accepted", rejected: "rejected", cancelled: "cancelled" };
const GrowingTiming = ({ request, t }) => request.timing_model === "growing_period" && request.request_status === "accepted" ? <dl className="cultivation-timing-details"><div><dt>{t("growingPeriod.plannedCultivationStart")}</dt><dd>{request.planned_start_date || "—"}</dd></div><div><dt>{t("buyer.cultivation.requestedQuantity")}</dt><dd>{request.agreed_quantity} {request.unit}</dd></div><div><dt>{t("orderPresentation.unitPrice")}</dt><dd>Rs. {Number(request.agreed_unit_price).toFixed(2)} / {request.unit}</dd></div><div><dt>{t("buyer.cultivation.agreedTotal")}</dt><dd>Rs. {Number(request.agreed_total_amount).toFixed(2)}</dd></div><div><dt>{t("growingPeriod.label")}</dt><dd>~{request.agreed_growing_period_days ?? request.growing_period_days} {t("growingPeriod.units.days")}</dd></div><div><dt>{t("growingPeriod.actualStart")}</dt><dd>{request.cultivation_started_at ? String(request.cultivation_started_at).slice(0, 10) : t("growingPeriod.notStarted")}</dd></div>{request.planned_start_date && !request.cultivation_started_at && new Date().toISOString().slice(0,10) > request.planned_start_date && <div><dt>{t("growingPeriod.startDelayed")}</dt><dd>{t("growingPeriod.plannedStartPassed")}</dd></div>}{request.estimated_harvest_date && <div><dt>{t("growingPeriod.estimatedHarvest")}</dt><dd>{request.estimated_harvest_date}</dd></div>}<div><dt>{t("buyer.cultivation.collectionDate")}</dt><dd>{request.collection_date || t("growingPeriod.toBeConfirmed")}</dd></div></dl> : null;
export default function CultivationRequests() {
  const { t } = useTranslation(); const navigate = useNavigate(); const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [page, setPage] = useState(1); const [busyId, setBusyId] = useState(null);
  const load = useCallback(() => { setLoading(true); return fetch("/backend/Apis/buyer/cultivationRequests/getMyCultivationRequests.php", { credentials: "include" }).then(readCultivationResponse).then((result) => { setRequests(result.data.requests); setError(""); }).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { load(); }, [load]); const pages = Math.max(1, Math.ceil(requests.length / PAGE_SIZE)); const visible = useMemo(() => requests.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE), [requests, page]);
  const cancel = async (id) => { if (busyId !== null || !confirm(t("buyer.cultivation.cancelConfirm"))) return; setBusyId(id); setError(""); try { const response = await fetch("/backend/Apis/buyer/cultivationRequests/cancelCultivationRequest.php", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cultivation_request_id: id }) }); await readCultivationResponse(response); await load(); } catch (caught) { setError(caught.message); } finally { setBusyId(null); } };
  return <section className="cultivation-requests-page"><h1>{t("buyer.cultivation.requestsTitle")}</h1><p>{t("buyer.cultivation.requestsSubtitle")}</p>{loading ? <div className="cultivation-market-state">{t("buyer.cultivation.loading")}</div> : error ? <div className="cultivation-market-state error">{error}</div> : !requests.length ? <div className="cultivation-market-state">{t("buyer.cultivation.noRequests")}</div> : <><div className="cultivation-request-list">{visible.map((request) => <article key={request.cultivation_request_id}><div><h2>{request.crop_name}</h2><p>{request.farmer_name}</p></div><span className={`request-status ${request.request_status}`}>{t(`buyer.cultivation.statuses.${statusKeys[request.request_status]}`)}</span><GrowingTiming request={request} t={t} /><dl><div><dt>{t("buyer.cultivation.requestedQuantity")}</dt><dd>{request.requested_quantity} {request.unit}</dd></div>{request.timing_model !== "growing_period" && <div><dt>{t("buyer.cultivation.collectionDate")}</dt><dd>{request.requested_collection_date}</dd></div>}<div><dt>{t("buyer.cultivation.requestedDate")}</dt><dd>{String(request.requested_at).slice(0, 10)}</dd></div>{request.request_status === "accepted" && <div><dt>{t("buyer.cultivation.agreedTotal")}</dt><dd>Rs. {Number(request.agreed_total_amount).toFixed(2)}</dd></div>}</dl>{request.request_status === "accepted" && request.reservation_id ? <div className="cultivation-request-actions"><span className="awaiting-payment">{t("orderPresentation.orderCreated")}</span><button type="button" className="cultivation-primary" onClick={() => navigate("/buyer/BuyerOrderHistory")}>{t("orderPresentation.viewOrder")}</button></div> : request.request_status === "accepted" && <p className="awaiting-payment">{t("buyer.cultivation.awaitingActivation")}</p>}{request.request_status === "pending" && <button type="button" disabled={busyId === request.cultivation_request_id} onClick={() => cancel(request.cultivation_request_id)}>{t("buyer.cultivation.cancelRequest")}</button>}</article>)}</div>{pages > 1 && <div className="cultivation-pagination"><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>{t("buyer.cultivation.previous")}</button><span>{t("buyer.cultivation.page", { page, pages })}</span><button type="button" disabled={page === pages} onClick={() => setPage((value) => value + 1)}>{t("buyer.cultivation.next")}</button></div>}</>}</section>;
}
