import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useAuth } from "../../../src/context/AuthContext";
import { readCultivationResponse } from "./cultivationApi.js";
import "../csss/CultivationMarketplace.css";

const pathUrl = (path) => path ? (path.startsWith("/") ? path : `/${path}`) : null;
const safeNumber = (value) => Number.isFinite(Number(value)) ? Number(value) : 0;

export default function CultivationOpportunityDetails() {
  const { id } = useParams(); const { t } = useTranslation(); const { user } = useAuth(); const navigate = useNavigate();
  const [ad, setAd] = useState(null); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [quantity, setQuantity] = useState(""); const [date, setDate] = useState("");
  useEffect(() => { let active = true; fetch(`/backend/Apis/buyer/cultivationAds/getCultivationAds.php?id=${encodeURIComponent(id)}`).then(readCultivationResponse).then((result) => { if (active) { setAd(result.data.ad); setDate(result.data.ad.expected_harvest_date); } }).catch((caught) => active && setError(caught.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id]);
  const progress = useMemo(() => { const capacity = Math.max(0, safeNumber(ad?.capacity_quantity)); const committed = Math.min(capacity, Math.max(0, safeNumber(ad?.committed_quantity))); return capacity ? committed / capacity * 100 : 0; }, [ad]);
  const submit = async (event) => { event.preventDefault(); if(submitting)return; setError(""); setSuccess(""); if (!user) { navigate("/login"); return; } if (user.role !== "buyer") { setError(t("buyer.cultivation.buyerOnly")); return; } const requested = Number(quantity); if (requested <= 0 || requested > Number(ad.remaining_capacity)) { setError(t("buyer.cultivation.invalidQuantity")); return; } if (date < ad.expected_harvest_date) { setError(t("buyer.cultivation.invalidCollectionDate")); return; } setSubmitting(true); try { const response = await fetch("/backend/Apis/buyer/cultivationRequests/createCultivationRequest.php", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cultivation_ad_id: Number(id), requested_quantity: requested, requested_collection_date: date }) }); const result = await readCultivationResponse(response); setSuccess(result.message); setQuantity(""); } catch (caught) { setError(caught.message); } finally { setSubmitting(false); } };
  if (loading) return <div className="cultivation-detail-state">{t("buyer.cultivation.loading")}</div>;
  if (!ad) return <div className="cultivation-detail-state error"><p>{error || t("cultivationAudit.unavailable")}</p><button type="button" onClick={() => navigate("/browse?tab=cultivation")}>{t("buyer.cultivation.back")}</button></div>;
  return <main className="cultivation-detail"><button type="button" className="cultivation-back" onClick={() => navigate("/browse?tab=cultivation")}>← {t("buyer.cultivation.back")}</button><div className="cultivation-detail-grid"><section><div className="cultivation-gallery">{ad.photos?.length ? ad.photos.map((photo) => <img key={photo} src={pathUrl(photo)} alt={ad.crop_name} />) : <div role="img" aria-label={t("buyer.cultivation.futureOpportunity")}>🌱</div>}</div><span className="cultivation-eyebrow">{t("buyer.cultivation.futureOpportunity")}</span><h1>{ad.crop_name}</h1><p className="cultivation-detail-farmer">✓ {ad.farmer_name} · {ad.district} · ★ {safeNumber(ad.farmer_rating).toFixed(1)}</p><p>{ad.description || t("buyer.cultivation.noDescription")}</p><div className="cultivation-detail-facts"><span>{t("buyer.cultivation.capacity")}<strong>{Math.max(0, safeNumber(ad.capacity_quantity))} {ad.unit}</strong></span><span>{t("buyer.cultivation.committed")}<strong>{Math.max(0, safeNumber(ad.committed_quantity))} {ad.unit}</strong></span><span>{t("buyer.cultivation.remaining")}<strong>{Math.max(0, safeNumber(ad.remaining_capacity))} {ad.unit}</strong></span><span>{t("buyer.cultivation.estimatedPrice")}<strong>Rs. {safeNumber(ad.estimated_unit_price).toFixed(2)} / {ad.unit}</strong></span><span>{t("buyer.cultivation.expectedHarvest")}<strong>{ad.expected_harvest_date}</strong></span>{ad.cultivation_area && <span>{t("buyer.cultivation.area")}<strong>{ad.cultivation_area} {ad.area_unit}</strong></span>}</div><div className="cultivation-market-progress"><div><i style={{ width: `${progress}%` }} /></div></div></section>
    <aside className="cultivation-request-panel"><h2>{t("buyer.cultivation.submitRequest")}</h2><p>{t("buyer.cultivation.paymentNote")}</p>{error && <div className="cultivation-form-message error">{error}</div>}{success && <div className="cultivation-form-message success">{success}</div>}<form onSubmit={submit}><label>{t("buyer.cultivation.requestedQuantity")} ({ad.unit})<input type="number" min="0.01" step="0.01" max={ad.remaining_capacity} value={quantity} onChange={(event) => setQuantity(event.target.value)} disabled={submitting} required /></label><label>{t("buyer.cultivation.collectionDate")}<input type="date" min={ad.expected_harvest_date} value={date} onChange={(event) => setDate(event.target.value)} disabled={submitting} required /></label><button type="submit" disabled={submitting}>{submitting ? t("farmer.cultivationAds.saving") : t("buyer.cultivation.submitRequest")}</button></form></aside></div></main>;
}
