<?php
require_once __DIR__.'/../../../connection/db.php';require_once __DIR__.'/../../auth_check.php';require_login();require_role('farmer');
$paymentId=(int)($_GET['payment_id']??0);if($paymentId<=0){http_response_code(400);exit('Invalid payment ID.');}
$farmerStmt=$pdo->prepare('SELECT farmer_id FROM farmer WHERE user_id=?');$farmerStmt->execute([$_SESSION['user']['id']]);$farmerId=(int)$farmerStmt->fetchColumn();
$stmt=$pdo->prepare("SELECT p.proof_file FROM payment p JOIN reservation r ON r.reservation_id=p.reservation_id LEFT JOIN reserve_crop rc ON r.reservation_source='crop' AND r.reserve_crop_id=rc.reserve_crop_id LEFT JOIN crop c ON rc.crop_id=c.crop_id LEFT JOIN cultivation_request cr ON r.reservation_source='cultivation' AND r.cultivation_request_id=cr.cultivation_request_id LEFT JOIN cultivation_ad ca ON cr.cultivation_ad_id=ca.cultivation_ad_id WHERE p.payment_id=? AND p.method='bank' AND ((r.reservation_source='crop' AND c.farmer_id=?) OR (r.reservation_source='cultivation' AND ca.farmer_id=?))");$stmt->execute([$paymentId,$farmerId,$farmerId]);$stored=$stmt->fetchColumn();
if(!$stored){http_response_code(404);exit('Receipt not found.');}$root=realpath(__DIR__.'/../../../storage/bank_receipts');$expectedPrefix='backend/storage/bank_receipts/';if(!$root||!str_starts_with(str_replace('\\','/',$stored),$expectedPrefix)){http_response_code(404);exit('Receipt not found.');}
$path=realpath($root.DIRECTORY_SEPARATOR.basename($stored));if(!$path||!is_file($path)||!str_starts_with($path,$root.DIRECTORY_SEPARATOR)){http_response_code(404);exit('Receipt not found.');}$mime=(new finfo(FILEINFO_MIME_TYPE))->file($path);$allowed=['image/jpeg','image/png','image/webp','application/pdf'];if(!in_array($mime,$allowed,true)){http_response_code(415);exit('Unsupported receipt type.');}
header('Content-Type: '.$mime);header('Content-Length: '.filesize($path));header('Content-Disposition: inline; filename="bank-receipt-'.$paymentId.'.'.pathinfo($path,PATHINFO_EXTENSION).'"');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');readfile($path);

