export const DISTRICTS = [
  { value: "Ampara", key: "ampara" },
  { value: "Anuradhapura", key: "anuradhapura" },
  { value: "Badulla", key: "badulla" },
  { value: "Batticaloa", key: "batticaloa" },
  { value: "Colombo", key: "colombo" },
  { value: "Galle", key: "galle" },
  { value: "Gampaha", key: "gampaha" },
  { value: "Hambantota", key: "hambantota" },
  { value: "Jaffna", key: "jaffna" },
  { value: "Kalutara", key: "kalutara" },
  { value: "Kandy", key: "kandy" },
  { value: "Kegalle", key: "kegalle" },
  { value: "Kilinochchi", key: "kilinochchi" },
  { value: "Kurunegala", key: "kurunegala" },
  { value: "Mannar", key: "mannar" },
  { value: "Matale", key: "matale" },
  { value: "Matara", key: "matara" },
  { value: "Monaragala", key: "monaragala" },
  { value: "Mullaitivu", key: "mullaitivu" },
  { value: "Nuwara Eliya", key: "nuwaraEliya" },
  { value: "Polonnaruwa", key: "polonnaruwa" },
  { value: "Puttalam", key: "puttalam" },
  { value: "Ratnapura", key: "ratnapura" },
  { value: "Trincomalee", key: "trincomalee" },
  { value: "Vavuniya", key: "vavuniya" }
];
