/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { readCultivationResponse } from "../../buyer/react/cultivationApi.js";
import "../../buyer/csss/CultivationAudit.css";
const PAGE_SIZE = 10;
const GrowingTiming = ({ request, t, label }) => request.timing_model === "growing_period" && request.request_status === "accepted" ? <dl><div><dt>{t("growingPeriod.label")}</dt><dd>~{request.agreed_growing_period_days ?? request.growing_period_days} {t("growingPeriod.units.days")}</dd></div><div><dt>{request.cultivation_started_at ? t("growingPeriod.cultivationStarted") : t("growingPeriod.cultivationNotStarted")}</dt><dd>{request.cultivation_started_at ? String(request.cultivation_started_at).slice(0, 10) : "—"}</dd></div>{request.estimated_harvest_date && <div><dt>{t("growingPeriod.estimatedHarvest")}</dt><dd>{request.estimated_harvest_date}</dd></div>}<div><dt>{label}</dt><dd>{t("growingPeriod.toBeConfirmed")}</dd></div></dl> : null;
export default function CultivationRequests() {
  const { t } = useTranslation(); const text = (key, values) => t(`farmer.cultivationRequests.${key}`, values); const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [page, setPage] = useState(1); const [busyId, setBusyId] = useState(null);
  const load = useCallback(() => { setLoading(true); return fetch("/backend/Apis/farmer/cultivationRequests/getMyCultivationRequests.php", { credentials: "include" }).then(readCultivationResponse).then((result) => { setRequests(result.data.requests); setError(""); }).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { load(); }, [load]); const pages = Math.max(1, Math.ceil(requests.length / PAGE_SIZE)); const visible = useMemo(() => requests.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE), [requests, page]);
  const respond = async (id, action) => { if (busyId !== null || !confirm(text(`${action}Confirm`))) return; setBusyId(id); setError(""); try { const response = await fetch(`/backend/Apis/farmer/cultivationRequests/${action}CultivationRequest.php`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cultivation_request_id: id }) }); await readCultivationResponse(response); await load(); } catch (caught) { setError(caught.message); } finally { setBusyId(null); } };
  if (loading) return <div className="cultivation-state">{text("loading")}</div>;
  return <div>{error && <div className="cultivation-error">{error}</div>}{!requests.length ? <div className="cultivation-empty">{text("empty")}</div> : <><div className="cultivation-request-list farmer-cultivation-requests">{visible.map((request) => <article key={request.cultivation_request_id}><div><h2>{request.crop_name}</h2><p>{request.buyer_name}</p></div><b className={`request-status ${request.request_status}`}>{text(`statuses.${request.request_status}`)}</b><GrowingTiming request={request} t={t} label={text("collectionDate")} /><dl><div><dt>{text("requestedQuantity")}</dt><dd>{request.requested_quantity} {request.unit}</dd></div>{request.timing_model !== "growing_period" && <div><dt>{text("collectionDate")}</dt><dd>{request.requested_collection_date}</dd></div>}<div><dt>{text("requestDate")}</dt><dd>{String(request.requested_at).slice(0, 10)}</dd></div><div><dt>{text("remaining")}</dt><dd>{request.remaining_capacity} {request.unit}</dd></div></dl>{request.request_status === "pending" && <div className="cultivation-request-actions"><button type="button" disabled={busyId === request.cultivation_request_id} className="cultivation-primary" onClick={() => respond(request.cultivation_request_id, "accept")}>{text("accept")}</button><button type="button" disabled={busyId === request.cultivation_request_id} className="cultivation-close" onClick={() => respond(request.cultivation_request_id, "reject")}>{text("reject")}</button></div>}</article>)}</div>{pages > 1 && <div className="cultivation-pagination"><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>{text("previous")}</button><span>{text("page", { page, pages })}</span><button type="button" disabled={page === pages} onClick={() => setPage((value) => value + 1)}>{text("next")}</button></div>}</>}</div>;
}
