/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import CultivationRequests from "./CultivationRequests.jsx";
import "../csss/CultivationAds.css";
import "../csss/CultivationRequests.css";
const statusKeys={draft:"draft",open:"open",capacity_reached:"fullyCommitted",cultivating:"cultivating",harvested:"harvested",cancelled:"cancelled",closed:"closed"};
export default function CultivationOpportunities(){const navigate=useNavigate();const{t}=useTranslation();const text=(key,fallback)=>t(`farmer.cultivationAds.${key}`,{defaultValue:fallback});const[ads,setAds]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[activeTab,setActiveTab]=useState(()=>new URLSearchParams(window.location.search).get("tab")==="requests"?"requests":"ads");
const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/backend/Apis/farmer/cultivationAds/getMyCultivationAds.php",{credentials:"include"});const result=await response.json();if(!result.success)throw new Error(result.message);setAds(result.data.ads);setError("");}catch(e){setError(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
const close=async ad=>{if(!confirm(text("closeConfirm","Close this cultivation opportunity?")))return;const response=await fetch("/backend/Apis/farmer/cultivationAds/closeCultivationAd.php",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({cultivation_ad_id:ad.cultivation_ad_id})});const result=await response.json();if(!result.success)return alert(result.message);load()};
if(loading)return<div className="cultivation-state">{text("loading","Loading...")}</div>;return <section className="cultivation-page"><div className="cultivation-list-header"><div><h1>{text("opportunitiesTitle","Cultivation Opportunities")}</h1><p>{text("manageSubtitle","Manage future cultivation capability separately from current crop stock.")}</p></div><button className="cultivation-primary" onClick={()=>navigate("/farmer/add-cultivation-ad")}>{text("addTitle","Add Cultivation Ad")}</button></div><div className="cultivation-management-tabs"><button className={activeTab==="ads"?"active":""} onClick={()=>setActiveTab("ads")}>{text("myAds","My Ads")}</button><button className={activeTab==="requests"?"active":""} onClick={()=>setActiveTab("requests")}>{t("farmer.cultivationRequests.title")}</button></div>{activeTab==="requests"?<CultivationRequests/>:<>{error&&<div className="cultivation-error">{error}</div>}{!error&&!ads.length&&<div className="cultivation-empty">{text("empty","No cultivation opportunities yet")}</div>}<div className="cultivation-grid">{ads.map(ad=>{const capacity=Number(ad.capacity_quantity),committed=Number(ad.committed_quantity),remaining=Math.max(0,Number(ad.remaining_capacity));const progress=Math.min(100,Math.max(0,capacity?committed/capacity*100:0));const editable=["draft","open","cultivating"].includes(ad.status);return <article className="cultivation-card" key={ad.cultivation_ad_id}>{ad.primary_photo?<img className="cultivation-card-image" src={`/${ad.primary_photo}`} alt={ad.crop_name}/>:<div className="cultivation-card-image cultivation-placeholder">🌱</div>}<div className="cultivation-card-body"><div className="cultivation-card-title"><div><h2>{ad.crop_name}</h2><span>{ad.district} · {ad.category}</span></div><b className={`cultivation-status status-${ad.status}`}>{text(`statuses.${statusKeys[ad.status]}`,ad.status)}</b></div><div className="cultivation-facts"><span>{text("estimatedPrice","Estimated Price")}<strong>Rs. {Number(ad.estimated_unit_price).toFixed(2)} / {ad.unit}</strong></span><span>{text("expectedHarvest","Expected Harvest Date")}<strong>{ad.expected_harvest_date}</strong></span></div><div className="capacity-block"><div><strong>{text("capacityCommitment","Capacity Commitment")}</strong><span>{committed} / {capacity} {ad.unit} {text("committed","committed")}</span></div><div className="capacity-track"><i style={{width:`${progress}%`}}/></div><p>{remaining} {ad.unit} {text("available","available")}</p></div><small>{text("created","Created")}: {String(ad.created_at).slice(0,10)}</small><div className="cultivation-card-actions">{editable&&<button className="cultivation-secondary" onClick={()=>navigate(`/farmer/edit-cultivation-ad/${ad.cultivation_ad_id}`)}>{text("edit","Edit")}</button>}{ad.status==="open"&&<button className="cultivation-close" onClick={()=>close(ad)}>{text("closeOpportunity","Close Opportunity")}</button>}</div></div></article>})}</div></>}</section>}
