/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { readCultivationResponse } from "../../buyer/react/cultivationApi.js";
import "../../buyer/csss/CultivationAudit.css";
const PAGE_SIZE = 10;
const today = () => new Date().toISOString().slice(0, 10);
const isDelayed = (request) => request.planned_start_date && !request.cultivation_started_at && today() > request.planned_start_date;
const GrowingTiming = ({ request, t, label }) => request.timing_model === "growing_period" && request.request_status === "accepted" ? <dl className="cultivation-timing-details"><div><dt>{t("growingPeriod.plannedStart")}</dt><dd>{request.planned_start_date || "—"}</dd></div><div><dt>{t("growingPeriod.label")}</dt><dd>~{request.agreed_growing_period_days ?? request.growing_period_days} {t("growingPeriod.units.days")}</dd></div><div><dt>{t("growingPeriod.actualStart")}</dt><dd>{request.cultivation_started_at ? String(request.cultivation_started_at).slice(0, 10) : t("growingPeriod.notStarted")}</dd></div>{isDelayed(request) && <div><dt>{t("growingPeriod.startDelayed")}</dt><dd>{t("growingPeriod.plannedStartPassed")}</dd></div>}{request.estimated_harvest_date && <div><dt>{t("growingPeriod.estimatedHarvest")}</dt><dd>{request.estimated_harvest_date}</dd></div>}<div><dt>{label}</dt><dd>{request.collection_date || t("growingPeriod.toBeConfirmed")}</dd></div></dl> : null;
export default function CultivationRequests() {
  const { t } = useTranslation(); const text = (key, values) => t(`farmer.cultivationRequests.${key}`, values);
  const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [page, setPage] = useState(1); const [busyId, setBusyId] = useState(null); const [acceptingRequest, setAcceptingRequest] = useState(null); const [plannedStart, setPlannedStart] = useState("");
  const load = useCallback(() => { setLoading(true); return fetch("/backend/Apis/farmer/cultivationRequests/getMyCultivationRequests.php", { credentials: "include" }).then(readCultivationResponse).then((result) => { setRequests(result.data.requests); setError(""); }).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { load(); }, [load]); const pages = Math.max(1, Math.ceil(requests.length / PAGE_SIZE)); const visible = useMemo(() => requests.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE), [requests, page]);
  const submitResponse = async (request, action, date = "") => { if (busyId !== null) return; setBusyId(request.cultivation_request_id); setError(""); try { const response = await fetch(`/backend/Apis/farmer/cultivationRequests/${action}CultivationRequest.php`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cultivation_request_id: request.cultivation_request_id, ...(date ? { planned_start_date: date } : {}) }) }); await readCultivationResponse(response); setAcceptingRequest(null); setPlannedStart(""); await load(); } catch (caught) { setError(caught.message); } finally { setBusyId(null); } };
  const respond = (request, action) => { if (action === "accept" && request.timing_model === "growing_period" && !request.planned_start_date) { setAcceptingRequest(request); setPlannedStart(""); return; } if (confirm(text(`${action}Confirm`))) submitResponse(request, action); };
  if (loading) return <div className="cultivation-state">{text("loading")}</div>;
  return <div>{error && <div className="cultivation-error">{error}</div>}{!requests.length ? <div className="cultivation-empty">{text("empty")}</div> : <><div className="cultivation-request-list farmer-cultivation-requests">{visible.map((request) => <article key={request.cultivation_request_id}><div><h2>{request.crop_name}</h2><p>{request.buyer_name}</p></div><b className={`request-status ${request.request_status}`}>{text(`statuses.${request.request_status}`)}</b><GrowingTiming request={request} t={t} label={text("collectionDate")} /><dl><div><dt>{text("requestedQuantity")}</dt><dd>{request.requested_quantity} {request.unit}</dd></div>{request.timing_model !== "growing_period" && <div><dt>{text("collectionDate")}</dt><dd>{request.requested_collection_date}</dd></div>}<div><dt>{text("requestDate")}</dt><dd>{String(request.requested_at).slice(0, 10)}</dd></div><div><dt>{text("remaining")}</dt><dd>{request.remaining_capacity} {request.unit}</dd></div>{request.request_status === "pending" && request.planned_start_date && <div><dt>{t("growingPeriod.plannedStart")}</dt><dd>{request.planned_start_date}</dd></div>}</dl>{request.request_status === "pending" && <div className="cultivation-request-actions">{request.ad_status === "open" && Number(request.requested_quantity) <= Number(request.remaining_capacity) && <button type="button" disabled={busyId === request.cultivation_request_id} className="cultivation-primary" onClick={() => respond(request, "accept")}>{text("accept")}</button>}<button type="button" disabled={busyId === request.cultivation_request_id} className="cultivation-close" onClick={() => respond(request, "reject")}>{text("reject")}</button></div>}</article>)}</div>{pages > 1 && <div className="cultivation-pagination"><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>{text("previous")}</button><span>{text("page", { page, pages })}</span><button type="button" disabled={page === pages} onClick={() => setPage((value) => value + 1)}>{text("next")}</button></div>}</>}{acceptingRequest && <div className="collection-date-modal" role="dialog" aria-modal="true" aria-labelledby="planned-start-title"><div className="collection-date-panel"><h3 id="planned-start-title">{text("accept")}</h3><p>{text("requestedQuantity")}: <strong>{acceptingRequest.requested_quantity} {acceptingRequest.unit}</strong></p><label>{t("growingPeriod.plannedCultivationStart")}<input type="date" min={today()} value={plannedStart} onChange={(event) => setPlannedStart(event.target.value)} /></label><div className="collection-date-actions"><button type="button" onClick={() => { setAcceptingRequest(null); setPlannedStart(""); }}>{t("buttons.cancel")}</button><button type="button" className="cultivation-primary" disabled={!plannedStart || busyId !== null} onClick={() => submitResponse(acceptingRequest, "accept", plannedStart)}>{t("growingPeriod.confirmAcceptance")}</button></div></div></div>}</div>;
}
